package me.tbsten.debuggable.runtime.annotations

/**
 * Marks APIs in `debuggable-runtime` that are only intended to be called from
 * code generated by the Debuggable compiler plugin — not from user code.
 *
 * These symbols are `public` because the compiler plugin emits references to
 * them as JVM-visible calls into the runtime classpath. Marking them with this
 * annotation keeps them out of day-to-day IDE autocomplete and surfaces a
 * compile-time warning if a user accidentally calls them directly.
 *
 * The compiler plugin itself bypasses this check because it emits IR directly
 * at the backend, past the frontend's opt-in enforcement.
 */
@RequiresOptIn(
    message = "This API is only intended to be called from code generated by the Debuggable compiler plugin. " +
        "If you really need to call it from user code, opt-in explicitly with @OptIn(InternalDebuggableApi::class).",
    level = RequiresOptIn.Level.WARNING,
)
@Retention(AnnotationRetention.BINARY)
@Target(
    AnnotationTarget.CLASS,
    AnnotationTarget.FUNCTION,
    AnnotationTarget.PROPERTY,
    AnnotationTarget.TYPEALIAS,
)
public annotation class InternalDebuggableApi
