#!/usr/bin/env bash
#
# smoke-test.sh — build the CMP sample against a target Kotlin version and verify
#                 that the Debuggable compiler plugin injected the expected symbols
#                 into the generated bytecode.
#
# Usage:
#   ./scripts/smoke-test.sh <kotlin-version> [cmp-workdir]
#
# Example:
#   ./scripts/smoke-test.sh 2.3.20
#   ./scripts/smoke-test.sh 2.2.20 .local/tmp/cmp-2.2.20
#
# Optional second argument (or `SMOKE_CMP_WORKDIR` env var) points at a copy of
# `integration-test/cmp/` to build in, so parallel runs don't clash on the
# shared `build/` directory. When unset, the in-repo `integration-test/cmp/`
# is used directly (the original serial behaviour).
#
# Optional `SMOKE_SKIP_PUBLISH=1` skips step 1 — the caller guarantees that
# `publishToMavenLocal` already ran once upstream (used by smoke-test-all.sh
# to avoid N workers racing on `~/.m2/`).
#
# Exits 0 on success, non-zero on any failure. Meant to be called from CI and
# from local dev. Assumes the plugin and runtime are publishable from repo root
# (this script handles the publish step automatically).

set -euo pipefail

kotlin_version="${1:-}"
if [[ -z "$kotlin_version" ]]; then
    echo "Usage: $0 <kotlin-version> [cmp-workdir]" >&2
    exit 2
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

cmp_workdir="${2:-${SMOKE_CMP_WORKDIR:-integration-test/cmp}}"
if [[ ! -d "$cmp_workdir" ]]; then
    echo "FAIL: cmp workdir not found: $cmp_workdir" >&2
    exit 1
fi

log_dir=".local/tmp"
mkdir -p "$log_dir"
log_prefix="$log_dir/smoke-$(date +%Y%m%d-%H%M%S)-kotlin-$kotlin_version"

echo "=== [smoke-test] Kotlin $kotlin_version ==="
echo "Logs: $log_prefix.*.log"

if [[ "${SMOKE_SKIP_PUBLISH:-0}" == "1" ]]; then
    echo
    echo "--- Step 1/4: publishToMavenLocal (skipped via SMOKE_SKIP_PUBLISH=1) ---"
else
    echo
    echo "--- Step 1/4: publishToMavenLocal (plugin itself is compiled with its own pinned Kotlin) ---"
    ./gradlew publishToMavenLocal \
        --no-daemon \
        > "$log_prefix.publish.log" 2>&1 || {
        echo "FAIL: publishToMavenLocal failed. See $log_prefix.publish.log" >&2
        tail -50 "$log_prefix.publish.log" >&2
        exit 1
    }
    echo "ok."
fi

echo
echo "--- Step 2/4: build $cmp_workdir with Kotlin=$kotlin_version ---"
(
    cd "$cmp_workdir"
    ./gradlew build \
        "-Pintegration.kotlin=$kotlin_version" \
        --no-daemon \
        --refresh-dependencies \
        > "$repo_root/$log_prefix.cmp-build.log" 2>&1
) || {
    echo "FAIL: CMP sample build failed. See $log_prefix.cmp-build.log" >&2
    tail -50 "$log_prefix.cmp-build.log" >&2
    exit 1
}
echo "ok."

echo
echo "--- Step 3/4: verify bytecode contains injected Debuggable symbols ---"
class_file="$cmp_workdir/build/classes/kotlin/jvm/main/example/CounterStore.class"
if [[ ! -f "$class_file" ]]; then
    echo "FAIL: expected class file not found: $class_file" >&2
    exit 1
fi

bytecode_dump="$log_prefix.javap.txt"
javap -p -c "$class_file" > "$bytecode_dump" 2>&1 || {
    echo "FAIL: javap dump failed. See $bytecode_dump" >&2
    exit 1
}

missing=()
for symbol in "debuggableFlow" "logAction"; do
    if ! grep -q "$symbol" "$bytecode_dump"; then
        missing+=("$symbol")
    fi
done

if [[ ${#missing[@]} -gt 0 ]]; then
    echo "FAIL: expected symbols missing in bytecode: ${missing[*]}" >&2
    echo "Dump: $bytecode_dump" >&2
    exit 1
fi
echo "ok — bytecode contains: debuggableFlow, logAction"

echo
echo "--- Step 4/4: build integration-test/kmp-smoke (all KMP targets) with Kotlin=$kotlin_version ---"
# kmp-smoke exercises `@Debuggable` + `@FocusDebuggable var` + logAction via an
# InMemoryLogger. `jvmTest` asserts runtime behaviour; the per-target
# `compileKotlin<Target>` checks that the plugin JAR is self-contained enough
# to run on every KMP target's compiler-plugin-classpath (native / wasmJs / js
# filter out JVM-only transitive deps — fixed by shadowing compat into the
# main plugin JAR, tracked as `done/bug-002-native-plugin-classpath.md`).
kmp_workdir="${SMOKE_KMP_WORKDIR:-integration-test/kmp-smoke}"
(
    cd "$kmp_workdir"
    ./gradlew \
        jvmTest \
        compileKotlinJvm \
        compileKotlinJs \
        compileKotlinWasmJs \
        compileKotlinIosArm64 \
        compileKotlinIosSimulatorArm64 \
        compileKotlinMacosArm64 \
        compileKotlinLinuxX64 \
        compileKotlinMingwX64 \
        "-Pintegration.kotlin=$kotlin_version" \
        --no-daemon \
        --refresh-dependencies \
        --rerun-tasks \
        > "$repo_root/$log_prefix.kmp-smoke.log" 2>&1
) || {
    echo "FAIL: kmp-smoke test failed. See $log_prefix.kmp-smoke.log" >&2
    tail -50 "$log_prefix.kmp-smoke.log" >&2
    exit 1
}
echo "ok."

echo
echo "=== [smoke-test] PASS (Kotlin $kotlin_version) ==="
