#!/usr/bin/env bash
#
# smoke-test.sh — build the CMP sample against a target Kotlin version and verify
#                 that the Debuggable compiler plugin injected the expected symbols
#                 into the generated bytecode.
#
# Usage:
#   ./scripts/smoke-test.sh <kotlin-version>
#
# Example:
#   ./scripts/smoke-test.sh 2.3.20
#   ./scripts/smoke-test.sh 2.2.20
#
# Exits 0 on success, non-zero on any failure. Meant to be called from CI and
# from local dev. Assumes the plugin and runtime are publishable from repo root
# (this script handles the publish step automatically).

set -euo pipefail

kotlin_version="${1:-}"
if [[ -z "$kotlin_version" ]]; then
    echo "Usage: $0 <kotlin-version>" >&2
    exit 2
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

log_dir=".local/tmp"
mkdir -p "$log_dir"
log_prefix="$log_dir/smoke-$(date +%Y%m%d-%H%M%S)-kotlin-$kotlin_version"

echo "=== [smoke-test] Kotlin $kotlin_version ==="
echo "Logs: $log_prefix.*.log"

echo
echo "--- Step 1/3: publishToMavenLocal (plugin itself is compiled with its own pinned Kotlin) ---"
./gradlew publishToMavenLocal \
    --no-daemon \
    > "$log_prefix.publish.log" 2>&1 || {
    echo "FAIL: publishToMavenLocal failed. See $log_prefix.publish.log" >&2
    tail -50 "$log_prefix.publish.log" >&2
    exit 1
}
echo "ok."

echo
echo "--- Step 2/3: build integration-test/cmp with Kotlin=$kotlin_version ---"
(
    cd integration-test/cmp
    ./gradlew build \
        "-Pintegration.kotlin=$kotlin_version" \
        --no-daemon \
        --refresh-dependencies \
        > "$repo_root/$log_prefix.cmp-build.log" 2>&1
) || {
    echo "FAIL: CMP sample build failed. See $log_prefix.cmp-build.log" >&2
    tail -50 "$log_prefix.cmp-build.log" >&2
    exit 1
}
echo "ok."

echo
echo "--- Step 3/3: verify bytecode contains injected Debuggable symbols ---"
class_file="integration-test/cmp/build/classes/kotlin/jvm/main/example/CounterStore.class"
if [[ ! -f "$class_file" ]]; then
    echo "FAIL: expected class file not found: $class_file" >&2
    exit 1
fi

bytecode_dump="$log_prefix.javap.txt"
javap -p -c "$class_file" > "$bytecode_dump" 2>&1 || {
    echo "FAIL: javap dump failed. See $bytecode_dump" >&2
    exit 1
}

missing=()
for symbol in "debuggableFlow" "logAction"; do
    if ! grep -q "$symbol" "$bytecode_dump"; then
        missing+=("$symbol")
    fi
done

if [[ ${#missing[@]} -gt 0 ]]; then
    echo "FAIL: expected symbols missing in bytecode: ${missing[*]}" >&2
    echo "Dump: $bytecode_dump" >&2
    exit 1
fi
echo "ok — bytecode contains: debuggableFlow, logAction"

echo
echo "=== [smoke-test] PASS (Kotlin $kotlin_version) ==="
