#!/usr/bin/env bash
#
# verify-zero-overhead.sh — assert that when the Debuggable plugin is active
#                           but `debuggable.enabled=false` (configured via
#                           `debuggable { enabled.set(false) }` on the
#                           consumer), the generated bytecode contains NO
#                           Debuggable-injected symbols.
#
# Related: task-415 (`enabled=false` complete no-op) and task-416 (jar-level
# zero-overhead assertion). This is the "negative" counterpart of
# `scripts/smoke-test.sh` step 3.
#
# Usage:
#   ./scripts/verify-zero-overhead.sh <kotlin-version> [cmp-workdir]
#
# The script expects the consumer project at `cmp-workdir` to honour the
# `-Pdebuggable.enabled=false` Gradle property (the Debuggable Gradle plugin
# reads this into the extension). If your consumer hard-codes `enabled=true`
# this script cannot verify zero-overhead — adjust the consumer first.
#
# Exits 0 if the expected symbols are ABSENT, non-zero otherwise.

set -euo pipefail

kotlin_version="${1:-}"
if [[ -z "$kotlin_version" ]]; then
    echo "Usage: $0 <kotlin-version> [cmp-workdir]" >&2
    exit 2
fi

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

cmp_workdir="${2:-integration-test/cmp}"
if [[ ! -d "$cmp_workdir" ]]; then
    echo "FAIL: cmp workdir not found: $cmp_workdir" >&2
    exit 1
fi

log_dir=".local/tmp"
mkdir -p "$log_dir"
log_prefix="$log_dir/zero-overhead-$(date +%Y%m%d-%H%M%S)-kotlin-$kotlin_version"

echo "=== [verify-zero-overhead] Kotlin $kotlin_version ==="
echo "Logs: $log_prefix.*.log"

echo
echo "--- Step 1/3: publishToMavenLocal ---"
./gradlew publishToMavenLocal --no-daemon \
    > "$log_prefix.publish.log" 2>&1 || {
    echo "FAIL: publishToMavenLocal failed. See $log_prefix.publish.log" >&2
    tail -50 "$log_prefix.publish.log" >&2
    exit 1
}
echo "ok."

echo
echo "--- Step 2/3: build $cmp_workdir with enabled=false ---"
(
    cd "$cmp_workdir"
    ./gradlew clean build \
        "-Pintegration.kotlin=$kotlin_version" \
        "-Pdebuggable.enabled=false" \
        --no-daemon \
        --refresh-dependencies \
        --rerun-tasks \
        > "$repo_root/$log_prefix.build.log" 2>&1
) || {
    echo "FAIL: CMP sample build failed. See $log_prefix.build.log" >&2
    tail -50 "$log_prefix.build.log" >&2
    exit 1
}
echo "ok."

echo
echo "--- Step 3/3: assert bytecode has NO injected Debuggable symbols ---"
class_file="$cmp_workdir/build/classes/kotlin/jvm/main/example/CounterStore.class"
if [[ ! -f "$class_file" ]]; then
    echo "FAIL: expected class file not found: $class_file" >&2
    exit 1
fi

bytecode_dump="$log_prefix.javap.txt"
javap -p -c "$class_file" > "$bytecode_dump" 2>&1 || {
    echo "FAIL: javap dump failed. See $bytecode_dump" >&2
    exit 1
}

unexpected=()
for symbol in "debuggableFlow" "logAction" '$$debuggable_registry'; do
    if grep -q -F "$symbol" "$bytecode_dump"; then
        unexpected+=("$symbol")
    fi
done

if [[ ${#unexpected[@]} -gt 0 ]]; then
    echo "FAIL: unexpected Debuggable symbols present with enabled=false: ${unexpected[*]}" >&2
    echo "Dump: $bytecode_dump" >&2
    exit 1
fi
echo "ok — bytecode contains none of: debuggableFlow, logAction, \$\$debuggable_registry"

echo
echo "=== [verify-zero-overhead] PASS (Kotlin $kotlin_version) ==="
